" Name:         Gruvbox 8 Hard
" Description:  Retro groove color scheme originally designed by morhetz
" Author:       morhetz <morhetz@gmail.com>
" Maintainer:   Lifepillar <lifepillar@lifepillar.me>
" Website:      https://github.com/lifepillar/vim-gruvbox8/
" License:      Vim License (see `:help license`)
" Last Updated: Tue Jan 19 20:21:48 2021

" Generated by Colortemplate v2.1.0

hi clear
let g:colors_name = 'gruvbox8_hard'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running') || has('nvim')

let s:italics = s:italics && get(g:, 'gruvbox_italics', 1)
hi! link CursorColumn CursorLine
hi! link QuickFixLine Search
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link VisualNOS Visual
hi! link Tag Special
hi! link lCursor Cursor
hi! link iCursor Cursor
hi! link vCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  if &background ==# 'dark'
    let g:terminal_ansi_colors = ['#1d2021', '#cc241d', '#98971a', '#d79921',
          \ '#458588', '#b16286', '#689d6a', '#a89984', '#928374', '#fb4934',
          \ '#b8bb26', '#fabd2f', '#83a598', '#d3869b', '#8ec07c', '#ebdbb2']
    if has('nvim')
      let g:terminal_color_0 = '#1d2021'
      let g:terminal_color_1 = '#cc241d'
      let g:terminal_color_2 = '#98971a'
      let g:terminal_color_3 = '#d79921'
      let g:terminal_color_4 = '#458588'
      let g:terminal_color_5 = '#b16286'
      let g:terminal_color_6 = '#689d6a'
      let g:terminal_color_7 = '#a89984'
      let g:terminal_color_8 = '#928374'
      let g:terminal_color_9 = '#fb4934'
      let g:terminal_color_10 = '#b8bb26'
      let g:terminal_color_11 = '#fabd2f'
      let g:terminal_color_12 = '#83a598'
      let g:terminal_color_13 = '#d3869b'
      let g:terminal_color_14 = '#8ec07c'
      let g:terminal_color_15 = '#ebdbb2'
    endif
    if get(g:, 'gruvbox_transp_bg', 0) && !has('gui_running')
      hi Normal guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi CursorLineNr guifg=#7c6f64 guibg=NONE gui=NONE cterm=NONE
      hi FoldColumn guifg=#928374 guibg=NONE gui=NONE cterm=NONE
      hi SignColumn guifg=NONE guibg=NONE gui=NONE cterm=NONE
      hi VertSplit guifg=#665c54 guibg=NONE gui=NONE cterm=NONE
    else
      hi Normal guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi CursorLineNr guifg=#7c6f64 guibg=NONE gui=NONE cterm=NONE
      hi FoldColumn guifg=#928374 guibg=NONE gui=NONE cterm=NONE
      hi SignColumn guifg=NONE guibg=NONE gui=NONE cterm=NONE
      hi VertSplit guifg=#665c54 guibg=NONE gui=NONE cterm=NONE
    endif
    hi ColorColumn guifg=NONE guibg=#3c3836 gui=NONE cterm=NONE
    hi Comment guifg=#928374 guibg=NONE gui=italic cterm=italic
    hi CursorLine guifg=NONE guibg=#3c3836 gui=NONE cterm=NONE
    hi Error guifg=#fb4934 guibg=#1d2021 gui=bold,reverse cterm=bold,reverse
    hi ErrorMsg guifg=#1d2021 guibg=#fb4934 gui=bold cterm=bold
    hi Folded guifg=#928374 guibg=#3c3836 gui=italic cterm=italic
    hi LineNr guifg=#7c6f64 guibg=NONE gui=NONE cterm=NONE
    hi MatchParen guifg=NONE guibg=#665c54 gui=bold,underline cterm=bold,underline
    hi NonText guifg=#504945 guibg=NONE gui=NONE cterm=NONE
    hi Pmenu guifg=#ebdbb2 guibg=#504945 gui=NONE cterm=NONE
    hi PmenuSbar guifg=NONE guibg=#504945 gui=NONE cterm=NONE
    hi PmenuSel guifg=#504945 guibg=#83a598 gui=bold cterm=bold
    hi PmenuThumb guifg=NONE guibg=#7c6f64 gui=NONE cterm=NONE
    hi SpecialKey guifg=#928374 guibg=NONE gui=NONE cterm=NONE
    hi StatusLine guifg=#504945 guibg=#ebdbb2 gui=reverse cterm=reverse
    hi StatusLineNC guifg=#3c3836 guibg=#a89984 gui=reverse cterm=reverse
    hi TabLine guifg=#7c6f64 guibg=#3c3836 gui=NONE cterm=NONE
    hi TabLineFill guifg=#7c6f64 guibg=#3c3836 gui=NONE cterm=NONE
    hi TabLineSel guifg=#b8bb26 guibg=#3c3836 gui=NONE cterm=NONE
    hi ToolbarButton guifg=#fbf1c7 guibg=#665c54 gui=bold cterm=bold
    hi ToolbarLine guifg=NONE guibg=#665c54 gui=NONE cterm=NONE
    hi Visual guifg=NONE guibg=#665c54 gui=NONE cterm=NONE
    hi WildMenu guifg=#83a598 guibg=#504945 gui=bold cterm=bold
    hi Conceal guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
    hi Cursor guifg=NONE guibg=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
    hi DiffAdd guifg=#b8bb26 guibg=#1d2021 gui=reverse cterm=reverse
    hi DiffChange guifg=#8ec07c guibg=#1d2021 gui=reverse cterm=reverse
    hi DiffDelete guifg=#fb4934 guibg=#1d2021 gui=reverse cterm=reverse
    hi DiffText guifg=#fabd2f guibg=#1d2021 gui=reverse cterm=reverse
    hi Directory guifg=#b8bb26 guibg=NONE gui=bold cterm=bold
    hi EndOfBuffer guifg=#1d2021 guibg=NONE gui=NONE cterm=NONE
    hi IncSearch guifg=#fe8019 guibg=#1d2021 gui=reverse cterm=reverse
    hi ModeMsg guifg=#fabd2f guibg=NONE gui=bold cterm=bold
    hi MoreMsg guifg=#fabd2f guibg=NONE gui=bold cterm=bold
    hi Question guifg=#fe8019 guibg=NONE gui=bold cterm=bold
    hi Search guifg=#fabd2f guibg=#1d2021 gui=reverse cterm=reverse
    hi SpellBad guifg=#fb4934 guibg=NONE guisp=#fb4934 gui=italic,undercurl cterm=italic,underline
    hi SpellCap guifg=#83a598 guibg=NONE guisp=#83a598 gui=italic,undercurl cterm=italic,underline
    hi SpellLocal guifg=#8ec07c guibg=NONE guisp=#8ec07c gui=italic,undercurl cterm=italic,underline
    hi SpellRare guifg=#d3869b guibg=NONE guisp=#d3869b gui=italic,undercurl cterm=italic,underline
    hi Title guifg=#b8bb26 guibg=NONE gui=bold cterm=bold
    hi WarningMsg guifg=#fb4934 guibg=NONE gui=bold cterm=bold
    hi Boolean guifg=#d3869b guibg=NONE gui=NONE cterm=NONE
    hi Character guifg=#d3869b guibg=NONE gui=NONE cterm=NONE
    hi Conditional guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
    hi Constant guifg=#d3869b guibg=NONE gui=NONE cterm=NONE
    hi Define guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
    hi Debug guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
    hi Delimiter guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
    hi Error guifg=#fb4934 guibg=#1d2021 gui=bold,reverse cterm=bold,reverse
    hi Exception guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
    hi Float guifg=#d3869b guibg=NONE gui=NONE cterm=NONE
    hi Function guifg=#b8bb26 guibg=NONE gui=bold cterm=bold
    hi Identifier guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
    hi Ignore guifg=fg guibg=NONE gui=NONE cterm=NONE
    hi Include guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
    hi Keyword guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
    hi Label guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
    hi Macro guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
    hi Number guifg=#d3869b guibg=NONE gui=NONE cterm=NONE
    hi Operator guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
    hi PreCondit guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
    hi PreProc guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
    hi Repeat guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
    hi SpecialChar guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
    hi SpecialComment guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
    hi Statement guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
    hi StorageClass guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
    hi Special guifg=#fe8019 guibg=NONE gui=italic cterm=italic
    hi String guifg=#b8bb26 guibg=NONE gui=italic cterm=italic
    hi Structure guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
    hi Todo guifg=fg guibg=#1d2021 gui=bold,italic cterm=bold,italic
    hi Type guifg=#fabd2f guibg=NONE gui=NONE cterm=NONE
    hi Typedef guifg=#fabd2f guibg=NONE gui=NONE cterm=NONE
    hi Underlined guifg=#83a598 guibg=NONE gui=underline cterm=underline
    hi CursorIM guifg=NONE guibg=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
    if !s:italics
      hi Comment gui=NONE cterm=NONE
      hi Folded gui=NONE cterm=NONE
      hi SpellBad gui=undercurl cterm=underline
      hi SpellCap gui=undercurl cterm=underline
      hi SpellLocal gui=undercurl cterm=underline
      hi SpellRare gui=undercurl cterm=underline
      hi Special gui=NONE cterm=NONE
      hi String gui=NONE cterm=NONE
      hi Todo gui=bold cterm=bold
    endif
    if !get(g:, 'gruvbox_italicize_strings', 1)
      hi Special gui=NONE cterm=NONE
      hi String gui=NONE cterm=NONE
    endif
    if !get(g:, 'gruvbox_bold', 1)
      hi Directory gui=NONE cterm=NONE
      hi Error gui=reverse cterm=reverse
      hi ErrorMsg gui=NONE cterm=NONE
      hi Function gui=NONE cterm=NONE
      hi MatchParen gui=underline cterm=underline
      hi ModeMsg gui=NONE cterm=NONE
      hi MoreMsg gui=NONE cterm=NONE
      hi PmenuSel gui=NONE cterm=NONE
      hi Question gui=NONE cterm=NONE
      hi Title gui=NONE cterm=NONE
      hi Todo gui=italic cterm=italic
      hi ToolbarButton gui=NONE cterm=NONE
      hi WarningMsg gui=NONE cterm=NONE
      hi WildMenu gui=NONE cterm=NONE
    endif
    hi NormalMode guifg=#a89984 guibg=#1d2021 gui=reverse cterm=reverse
    hi InsertMode guifg=#83a598 guibg=#1d2021 gui=reverse cterm=reverse
    hi ReplaceMode guifg=#8ec07c guibg=#1d2021 gui=reverse cterm=reverse
    hi VisualMode guifg=#fe8019 guibg=#1d2021 gui=reverse cterm=reverse
    hi CommandMode guifg=#d3869b guibg=#1d2021 gui=reverse cterm=reverse
    hi Warnings guifg=#fe8019 guibg=#1d2021 gui=reverse cterm=reverse
    if has('nvim')
      hi! link TermCursor Cursor
      hi TermCursorNC guifg=#3c3836 guibg=#ebdbb2 gui=NONE cterm=NONE
    endif
    if !(get(g:, 'gruvbox_plugin_hi_groups', 0) || get(g:, 'gruvbox_filetype_hi_groups', 0))
      finish
    endif
    if get(g:, "gruvbox_plugin_hi_groups", 0)
      hi CocErrorSign guifg=#fb4934 guibg=#1d2021 gui=NONE cterm=NONE
      hi CocWarningSign guifg=#fabd2f guibg=#1d2021 gui=NONE cterm=NONE
      hi CocInfoSign guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi CocHintSign guifg=#504945 guibg=NONE gui=NONE cterm=NONE
      hi CocErrorFloat guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
      hi CocWarningFloat guifg=#fabd2f guibg=NONE gui=NONE cterm=NONE
      hi CocInfoFloat guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi CocHintFloat guifg=#d3869b guibg=NONE gui=NONE cterm=NONE
      hi CocSelectedText guifg=#3c3836 guibg=#1d2021 gui=NONE cterm=NONE
      hi CocCodeLens guifg=#504945 guibg=NONE gui=NONE cterm=NONE
    if get(g:, "gruvbox_filetype_hi_groups", 0)
      hi diffAdded guifg=#b8bb26 guibg=NONE gui=NONE cterm=NONE
      hi diffRemoved guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
      hi diffChanged guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi diffFile guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
      hi diffNewFile guifg=#fabd2f guibg=NONE gui=NONE cterm=NONE
      hi diffLine guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi htmlTag guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi htmlEndTag guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi htmlTagName guifg=#8ec07c guibg=NONE gui=bold cterm=bold
      hi htmlArg guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi htmlScriptTag guifg=#d3869b guibg=NONE gui=NONE cterm=NONE
      hi htmlTagN guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi htmlSpecialTagName guifg=#8ec07c guibg=NONE gui=bold cterm=bold
      hi htmlLink guifg=#a89984 guibg=NONE gui=underline cterm=underline
      hi htmlSpecialChar guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
      hi htmlBold guifg=fg guibg=#1d2021 gui=bold cterm=bold
      hi htmlBoldUnderline guifg=fg guibg=#1d2021 gui=bold,underline cterm=bold,underline
      hi htmlBoldItalic guifg=fg guibg=#1d2021 gui=bold,italic cterm=bold,italic
      hi htmlBoldUnderlineItalic guifg=fg guibg=#1d2021 gui=bold,italic,underline cterm=bold,italic,underline
      hi htmlUnderline guifg=fg guibg=#1d2021 gui=underline cterm=underline
      hi htmlUnderlineItalic guifg=fg guibg=#1d2021 gui=italic,underline cterm=italic,underline
      hi htmlItalic guifg=fg guibg=#1d2021 gui=italic cterm=italic
      hi xmlTag guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi xmlEndTag guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi xmlTagName guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi xmlEqual guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi docbkKeyword guifg=#8ec07c guibg=NONE gui=bold cterm=bold
      hi xmlDocTypeDecl guifg=#928374 guibg=NONE gui=NONE cterm=NONE
      hi xmlDocTypeKeyword guifg=#d3869b guibg=NONE gui=NONE cterm=NONE
      hi xmlCdataStart guifg=#928374 guibg=NONE gui=NONE cterm=NONE
      hi xmlCdataCdata guifg=#d3869b guibg=NONE gui=NONE cterm=NONE
      hi dtdFunction guifg=#928374 guibg=NONE gui=NONE cterm=NONE
      hi dtdTagName guifg=#d3869b guibg=NONE gui=NONE cterm=NONE
      hi xmlAttrib guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi xmlProcessingDelim guifg=#928374 guibg=NONE gui=NONE cterm=NONE
      hi dtdParamEntityPunct guifg=#928374 guibg=NONE gui=NONE cterm=NONE
      hi dtdParamEntityDPunct guifg=#928374 guibg=NONE gui=NONE cterm=NONE
      hi xmlAttribPunct guifg=#928374 guibg=NONE gui=NONE cterm=NONE
      hi xmlEntity guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
      hi xmlEntityPunct guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
      hi vimCommentTitle guifg=#a89984 guibg=NONE gui=bold cterm=bold
      hi vimNotation guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
      hi vimBracket guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
      hi vimMapModKey guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
      hi vimFuncSID guifg=#bdae93 guibg=NONE gui=NONE cterm=NONE
      hi vimSetSep guifg=#bdae93 guibg=NONE gui=NONE cterm=NONE
      hi vimSep guifg=#bdae93 guibg=NONE gui=NONE cterm=NONE
      hi vimContinue guifg=#bdae93 guibg=NONE gui=NONE cterm=NONE
      hi clojureKeyword guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi clojureCond guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
      hi clojureSpecial guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
      hi clojureDefine guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
      hi clojureFunc guifg=#fabd2f guibg=NONE gui=NONE cterm=NONE
      hi clojureRepeat guifg=#fabd2f guibg=NONE gui=NONE cterm=NONE
      hi clojureCharacter guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi clojureStringEscape guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi clojureException guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
      hi clojureRegexp guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi clojureRegexpEscape guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi clojureRegexpCharClass guifg=#bdae93 guibg=NONE gui=bold cterm=bold
      hi! link clojureRegexpMod clojureRegexpCharClass
      hi! link clojureRegexpQuantifier clojureRegexpCharClass
      hi clojureParen guifg=#bdae93 guibg=NONE gui=NONE cterm=NONE
      hi clojureAnonArg guifg=#fabd2f guibg=NONE gui=NONE cterm=NONE
      hi clojureVariable guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi clojureMacro guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
      hi clojureMeta guifg=#fabd2f guibg=NONE gui=NONE cterm=NONE
      hi clojureDeref guifg=#fabd2f guibg=NONE gui=NONE cterm=NONE
      hi clojureQuote guifg=#fabd2f guibg=NONE gui=NONE cterm=NONE
      hi clojureUnquote guifg=#fabd2f guibg=NONE gui=NONE cterm=NONE
      hi cOperator guifg=#d3869b guibg=NONE gui=NONE cterm=NONE
      hi cStructure guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
      hi pythonBuiltin guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
      hi pythonBuiltinObj guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
      hi pythonBuiltinFunc guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
      hi pythonFunction guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi pythonDecorator guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
      hi pythonInclude guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi pythonImport guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi pythonRun guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi pythonCoding guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi pythonOperator guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
      hi pythonException guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
      hi pythonExceptions guifg=#d3869b guibg=NONE gui=NONE cterm=NONE
      hi pythonBoolean guifg=#d3869b guibg=NONE gui=NONE cterm=NONE
      hi pythonDot guifg=#bdae93 guibg=NONE gui=NONE cterm=NONE
      hi pythonConditional guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
      hi pythonRepeat guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
      hi pythonDottedName guifg=#b8bb26 guibg=NONE gui=bold cterm=bold
      hi cssBraces guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi cssFunctionName guifg=#fabd2f guibg=NONE gui=NONE cterm=NONE
      hi cssIdentifier guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
      hi cssClassName guifg=#b8bb26 guibg=NONE gui=NONE cterm=NONE
      hi cssColor guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi cssSelectorOp guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi cssSelectorOp2 guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi cssImportant guifg=#b8bb26 guibg=NONE gui=NONE cterm=NONE
      hi cssVendor guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi cssTextProp guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi cssAnimationProp guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi cssUIProp guifg=#fabd2f guibg=NONE gui=NONE cterm=NONE
      hi cssTransformProp guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi cssTransitionProp guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi cssPrintProp guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi cssPositioningProp guifg=#fabd2f guibg=NONE gui=NONE cterm=NONE
      hi cssBoxProp guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi cssFontDescriptorProp guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi cssFlexibleBoxProp guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi cssBorderOutlineProp guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi cssBackgroundProp guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi cssMarginProp guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi cssListProp guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi cssTableProp guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi cssFontProp guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi cssPaddingProp guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi cssDimensionProp guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi cssRenderProp guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi cssColorProp guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi cssGeneratedContentProp guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi javaScriptBraces guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi javaScriptFunction guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi javaScriptIdentifier guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
      hi javaScriptMember guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi javaScriptNumber guifg=#d3869b guibg=NONE gui=NONE cterm=NONE
      hi javaScriptNull guifg=#d3869b guibg=NONE gui=NONE cterm=NONE
      hi javaScriptParens guifg=#bdae93 guibg=NONE gui=NONE cterm=NONE
      hi javascriptImport guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi javascriptExport guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi javascriptClassKeyword guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi javascriptClassExtends guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi javascriptDefault guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi javascriptClassName guifg=#fabd2f guibg=NONE gui=NONE cterm=NONE
      hi javascriptClassSuperName guifg=#fabd2f guibg=NONE gui=NONE cterm=NONE
      hi javascriptGlobal guifg=#fabd2f guibg=NONE gui=NONE cterm=NONE
      hi javascriptEndColons guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi javascriptFuncArg guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi javascriptGlobalMethod guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi javascriptNodeGlobal guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi javascriptBOMWindowProp guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi javascriptArrayMethod guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi javascriptArrayStaticMethod guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi javascriptCacheMethod guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi javascriptDateMethod guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi javascriptMathStaticMethod guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi javascriptURLUtilsProp guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi javascriptBOMNavigatorProp guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi javascriptDOMDocMethod guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi javascriptDOMDocProp guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi javascriptBOMLocationMethod guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi javascriptBOMWindowMethod guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi javascriptStringMethod guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi javascriptVariable guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
      hi javascriptIdentifier guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
      hi javascriptClassSuper guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
      hi javascriptFuncKeyword guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi javascriptAsyncFunc guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi javascriptClassStatic guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
      hi javascriptOperator guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
      hi javascriptForOperator guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
      hi javascriptYield guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
      hi javascriptExceptions guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
      hi javascriptMessage guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
      hi javascriptTemplateSB guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi javascriptTemplateSubstitution guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi javascriptLabel guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi javascriptObjectLabel guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi javascriptPropertyName guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi javascriptLogicSymbols guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi javascriptArrowFunc guifg=#fabd2f guibg=NONE gui=NONE cterm=NONE
      hi javascriptDocParamName guifg=#a89984 guibg=NONE gui=NONE cterm=NONE
      hi javascriptDocTags guifg=#a89984 guibg=NONE gui=NONE cterm=NONE
      hi javascriptDocNotation guifg=#a89984 guibg=NONE gui=NONE cterm=NONE
      hi javascriptDocParamType guifg=#a89984 guibg=NONE gui=NONE cterm=NONE
      hi javascriptDocNamedParamType guifg=#a89984 guibg=NONE gui=NONE cterm=NONE
      hi javascriptBrackets guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi javascriptDOMElemAttrs guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi javascriptDOMEventMethod guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi javascriptDOMNodeMethod guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi javascriptDOMStorageMethod guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi javascriptHeadersMethod guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi javascriptAsyncFuncKeyword guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
      hi javascriptAwaitFuncKeyword guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
      hi jsImport guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
      hi jsExport guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
      hi jsFrom guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
      hi jsThis guifg=#d3869b guibg=NONE gui=NONE cterm=NONE
      hi jsParen guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi jsOperator guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi jsSpreadOperator guifg=#b8bb26 guibg=NONE gui=NONE cterm=NONE
      hi jsSpreadExpression guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi jsClassKeyword guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
      hi jsClassProperty guifg=#b8bb26 guibg=NONE gui=NONE cterm=NONE
      hi jsExtendsKeyword guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
      hi jsExportDefault guifg=#fe8019 guibg=NONE gui=bold cterm=bold
      hi jsTemplateBraces guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi jsGlobalNodeObjects guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi jsGlobalObjects guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi jsFunction guifg=#b8bb26 guibg=NONE gui=NONE cterm=NONE
      hi jsFuncParens guifg=#d3869b guibg=NONE gui=NONE cterm=NONE
      hi jsFuncBlock guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi jsParens guifg=#bdae93 guibg=NONE gui=NONE cterm=NONE
      hi jsNull guifg=#d3869b guibg=NONE gui=NONE cterm=NONE
      hi jsUndefined guifg=#d3869b guibg=NONE gui=NONE cterm=NONE
      hi jsClassDefinition guifg=#fabd2f guibg=NONE gui=NONE cterm=NONE
      hi jsFunctionKey guifg=#b8bb26 guibg=NONE gui=NONE cterm=NONE
      hi jsBracket guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
      hi jsObjectColon guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
      hi jsObjectProp guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi jsFuncBraces guifg=#b8bb26 guibg=NONE gui=NONE cterm=NONE
      hi jsVariableDef guifg=#fabd2f guibg=NONE gui=NONE cterm=NONE
      hi jsObjectValue guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi jsDestructuringBlock guifg=#fabd2f guibg=NONE gui=NONE cterm=NONE
      hi jsParenIfElse guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi jsClassBlock guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi jsFutureKeys guifg=#fe8019 guibg=NONE gui=bold cterm=bold
      hi jsStorageClass guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
      hi jsModuleKeyword guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi jsObjectShorthandProp guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi jsxRegion guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi jsxTagName guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi jsxComponentName guifg=#fabd2f guibg=NONE gui=NONE cterm=NONE
      hi jsxEscapeJsAttributes guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi jsxEscapeJsContent guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi jsxAttrib guifg=#fabd2f guibg=NONE gui=NONE cterm=NONE
      hi jsxAttributeBraces guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi jsxEqual guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi jsxString guifg=#b8bb26 guibg=NONE gui=NONE cterm=NONE
      hi jsxCloseTag guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi jsxEndTag guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi jsxEndString guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi jsxCloseString guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi jsxIfOperator guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi jsxElseOperator guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi jsxDot guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi jsxNamespace guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi jsxPunct guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi typeScriptReserved guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi typeScriptLabel guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi typeScriptFuncKeyword guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi typeScriptIdentifier guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
      hi typeScriptBraces guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi typeScriptEndColons guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi typeScriptDOMObjects guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi typeScriptAjaxMethods guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi typeScriptLogicSymbols guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi! link typeScriptDocSeeTag Comment
      hi! link typeScriptDocParam Comment
      hi! link typeScriptDocTags vimCommentTitle
      hi typeScriptGlobalObjects guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi typeScriptParens guifg=#bdae93 guibg=NONE gui=NONE cterm=NONE
      hi typeScriptOpSymbols guifg=#bdae93 guibg=NONE gui=NONE cterm=NONE
      hi typeScriptHtmlElemProperties guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi typeScriptNull guifg=#d3869b guibg=NONE gui=NONE cterm=NONE
      hi typeScriptInterpolationDelimiter guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi purescriptModuleKeyword guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi purescriptModuleName guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi purescriptWhere guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi purescriptDelimiter guifg=#a89984 guibg=NONE gui=NONE cterm=NONE
      hi purescriptType guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi purescriptImportKeyword guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi purescriptHidingKeyword guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi purescriptAsKeyword guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi purescriptStructure guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi purescriptOperator guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi purescriptTypeVar guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi purescriptConstructor guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi purescriptFunction guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi purescriptConditional guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
      hi purescriptBacktick guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
      hi coffeeExtendedOp guifg=#bdae93 guibg=NONE gui=NONE cterm=NONE
      hi coffeeSpecialOp guifg=#bdae93 guibg=NONE gui=NONE cterm=NONE
      hi coffeeCurly guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
      hi coffeeParen guifg=#bdae93 guibg=NONE gui=NONE cterm=NONE
      hi coffeeBracket guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
      hi rubyStringDelimiter guifg=#b8bb26 guibg=NONE gui=NONE cterm=NONE
      hi rubyInterpolationDelimiter guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi objcTypeModifier guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
      hi objcDirective guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi goDirective guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi goConstants guifg=#d3869b guibg=NONE gui=NONE cterm=NONE
      hi goDeclaration guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
      hi goDeclType guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi goBuiltins guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
      hi luaIn guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
      hi luaFunction guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi luaTable guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
      hi moonSpecialOp guifg=#bdae93 guibg=NONE gui=NONE cterm=NONE
      hi moonExtendedOp guifg=#bdae93 guibg=NONE gui=NONE cterm=NONE
      hi moonFunction guifg=#bdae93 guibg=NONE gui=NONE cterm=NONE
      hi moonObject guifg=#fabd2f guibg=NONE gui=NONE cterm=NONE
      hi javaAnnotation guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi javaDocTags guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi! link javaCommentTitle vimCommentTitle
      hi javaParen guifg=#bdae93 guibg=NONE gui=NONE cterm=NONE
      hi javaParen1 guifg=#bdae93 guibg=NONE gui=NONE cterm=NONE
      hi javaParen2 guifg=#bdae93 guibg=NONE gui=NONE cterm=NONE
      hi javaParen3 guifg=#bdae93 guibg=NONE gui=NONE cterm=NONE
      hi javaParen4 guifg=#bdae93 guibg=NONE gui=NONE cterm=NONE
      hi javaParen5 guifg=#bdae93 guibg=NONE gui=NONE cterm=NONE
      hi javaOperator guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
      hi javaVarArg guifg=#b8bb26 guibg=NONE gui=NONE cterm=NONE
      hi! link elixirDocString Comment
      hi elixirStringDelimiter guifg=#b8bb26 guibg=NONE gui=NONE cterm=NONE
      hi elixirInterpolationDelimiter guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi elixirModuleDeclaration guifg=#fabd2f guibg=NONE gui=NONE cterm=NONE
      hi scalaNameDefinition guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi scalaCaseFollowing guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi scalaCapitalWord guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi scalaTypeExtension guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi scalaKeyword guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
      hi scalaKeywordModifier guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
      hi scalaSpecial guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi scalaOperator guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi scalaTypeDeclaration guifg=#fabd2f guibg=NONE gui=NONE cterm=NONE
      hi scalaTypeTypePostDeclaration guifg=#fabd2f guibg=NONE gui=NONE cterm=NONE
      hi scalaInstanceDeclaration guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi scalaInterpolation guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi markdownItalic guifg=#bdae93 guibg=NONE gui=italic cterm=italic
      hi markdownH1 guifg=#b8bb26 guibg=NONE gui=bold cterm=bold
      hi markdownH2 guifg=#b8bb26 guibg=NONE gui=bold cterm=bold
      hi markdownH3 guifg=#fabd2f guibg=NONE gui=bold cterm=bold
      hi markdownH4 guifg=#fabd2f guibg=NONE gui=bold cterm=bold
      hi markdownH5 guifg=#fabd2f guibg=NONE gui=NONE cterm=NONE
      hi markdownH6 guifg=#fabd2f guibg=NONE gui=NONE cterm=NONE
      hi markdownCode guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi markdownCodeBlock guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi markdownCodeDelimiter guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi markdownBlockquote guifg=#928374 guibg=NONE gui=NONE cterm=NONE
      hi markdownListMarker guifg=#928374 guibg=NONE gui=NONE cterm=NONE
      hi markdownOrderedListMarker guifg=#928374 guibg=NONE gui=NONE cterm=NONE
      hi markdownRule guifg=#928374 guibg=NONE gui=NONE cterm=NONE
      hi markdownHeadingRule guifg=#928374 guibg=NONE gui=NONE cterm=NONE
      hi markdownUrlDelimiter guifg=#bdae93 guibg=NONE gui=NONE cterm=NONE
      hi markdownLinkDelimiter guifg=#bdae93 guibg=NONE gui=NONE cterm=NONE
      hi markdownLinkTextDelimiter guifg=#bdae93 guibg=NONE gui=NONE cterm=NONE
      hi markdownHeadingDelimiter guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
      hi markdownUrl guifg=#d3869b guibg=NONE gui=NONE cterm=NONE
      hi markdownUrlTitleDelimiter guifg=#b8bb26 guibg=NONE gui=NONE cterm=NONE
      hi markdownLinkText guifg=#928374 guibg=NONE gui=underline cterm=underline
      hi! link markdownIdDeclaration markdownLinkText
      hi haskellType guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi haskellIdentifier guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi haskellSeparator guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi haskellDelimiter guifg=#a89984 guibg=NONE gui=NONE cterm=NONE
      hi haskellOperators guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
      hi haskellBacktick guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
      hi haskellStatement guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
      hi haskellConditional guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
      hi haskellLet guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi haskellDefault guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi haskellWhere guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi haskellBottom guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi haskellBlockKeywords guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi haskellImportKeywords guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi haskellDeclKeyword guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi haskellDeriving guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi haskellAssocType guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
      hi haskellNumber guifg=#d3869b guibg=NONE gui=NONE cterm=NONE
      hi haskellPragma guifg=#d3869b guibg=NONE gui=NONE cterm=NONE
      hi haskellString guifg=#b8bb26 guibg=NONE gui=NONE cterm=NONE
      hi haskellChar guifg=#b8bb26 guibg=NONE gui=NONE cterm=NONE
      hi jsonKeyword guifg=#b8bb26 guibg=NONE gui=NONE cterm=NONE
      hi jsonQuote guifg=#b8bb26 guibg=NONE gui=NONE cterm=NONE
      hi jsonBraces guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      hi jsonString guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
      if !s:italics
        hi htmlBoldItalic gui=bold cterm=bold
        hi htmlBoldUnderlineItalic gui=bold,underline cterm=bold,underline
        hi htmlUnderlineItalic gui=underline cterm=underline
        hi htmlItalic gui=NONE cterm=NONE
        hi markdownItalic gui=NONE cterm=NONE
      endif
      if !get(g:, 'gruvbox_bold', 1)
        hi htmlTagName gui=NONE cterm=NONE
        hi htmlSpecialTagName gui=NONE cterm=NONE
        hi htmlBold gui=NONE cterm=NONE
        hi htmlBoldUnderline gui=underline cterm=underline
        hi htmlBoldItalic gui=italic cterm=italic
        hi htmlBoldUnderlineItalic gui=underline,italic cterm=underline,italic
        hi docbkKeyword gui=NONE cterm=NONE
        hi vimCommentTitle gui=NONE cterm=NONE
        hi clojureRegexpCharClass gui=NONE cterm=NONE
        hi pythonDottedName gui=NONE cterm=NONE
        hi jsExportDefault gui=NONE cterm=NONE
        hi jsFutureKeys gui=NONE cterm=NONE
        hi markdownH1 gui=NONE cterm=NONE
        hi markdownH2 gui=NONE cterm=NONE
        hi markdownH3 gui=NONE cterm=NONE
        hi markdownH4 gui=NONE cterm=NONE
      endif
    endif
    unlet s:t_Co s:italics
    finish
  endif
  " Light background
  let g:terminal_ansi_colors = ['#f9f5d7', '#cc241d', '#98971a', '#d79921',
        \ '#458588', '#b16286', '#689d6a', '#7c6f64', '#928374', '#9d0006',
        \ '#79740e', '#b57614', '#076678', '#8f3f71', '#427b58', '#3c3836']
  if has('nvim')
    let g:terminal_color_0 = '#f9f5d7'
    let g:terminal_color_1 = '#cc241d'
    let g:terminal_color_2 = '#98971a'
    let g:terminal_color_3 = '#d79921'
    let g:terminal_color_4 = '#458588'
    let g:terminal_color_5 = '#b16286'
    let g:terminal_color_6 = '#689d6a'
    let g:terminal_color_7 = '#7c6f64'
    let g:terminal_color_8 = '#928374'
    let g:terminal_color_9 = '#9d0006'
    let g:terminal_color_10 = '#79740e'
    let g:terminal_color_11 = '#b57614'
    let g:terminal_color_12 = '#076678'
    let g:terminal_color_13 = '#8f3f71'
    let g:terminal_color_14 = '#427b58'
    let g:terminal_color_15 = '#3c3836'
  endif
  if get(g:, 'gruvbox_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi CursorLineNr guifg=NONE guibg=NONE gui=NONE cterm=NONE
    hi FoldColumn guifg=#928374 guibg=NONE gui=NONE cterm=NONE
    hi SignColumn guifg=NONE guibg=NONE gui=NONE cterm=NONE
    hi VertSplit guifg=#bdae93 guibg=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#3c3836 guibg=#f9f5d7 gui=NONE cterm=NONE
    hi CursorLineNr guifg=#b57614 guibg=#ebdbb2 gui=NONE cterm=NONE
    hi FoldColumn guifg=#928374 guibg=#ebdbb2 gui=NONE cterm=NONE
    hi SignColumn guifg=NONE guibg=NONE gui=NONE cterm=NONE
    hi VertSplit guifg=#bdae93 guibg=#f9f5d7 gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=NONE guibg=#ebdbb2 gui=NONE cterm=NONE
  hi Comment guifg=#928374 guibg=NONE gui=italic cterm=italic
  hi CursorLine guifg=NONE guibg=#ebdbb2 gui=NONE cterm=NONE
  hi Error guifg=#9d0006 guibg=#f9f5d7 gui=bold,reverse cterm=bold,reverse
  hi ErrorMsg guifg=#f9f5d7 guibg=#9d0006 gui=bold cterm=bold
  hi Folded guifg=#928374 guibg=#ebdbb2 gui=italic cterm=italic
  hi LineNr guifg=#a89984 guibg=NONE gui=NONE cterm=NONE
  hi MatchParen guifg=NONE guibg=#bdae93 gui=bold,underline cterm=bold,underline
  hi NonText guifg=#d5c4a1 guibg=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#3c3836 guibg=#d5c4a1 gui=NONE cterm=NONE
  hi PmenuSbar guifg=NONE guibg=#d5c4a1 gui=NONE cterm=NONE
  hi PmenuSel guifg=#d5c4a1 guibg=#076678 gui=bold cterm=bold
  hi PmenuThumb guifg=NONE guibg=#a89984 gui=NONE cterm=NONE
  hi SpecialKey guifg=#928374 guibg=NONE gui=NONE cterm=NONE
  hi StatusLine guifg=#d5c4a1 guibg=#3c3836 gui=reverse cterm=reverse
  hi StatusLineNC guifg=#ebdbb2 guibg=#7c6f64 gui=reverse cterm=reverse
  hi TabLine guifg=#a89984 guibg=#ebdbb2 gui=NONE cterm=NONE
  hi TabLineFill guifg=#a89984 guibg=#ebdbb2 gui=NONE cterm=NONE
  hi TabLineSel guifg=#79740e guibg=#ebdbb2 gui=NONE cterm=NONE
  hi ToolbarButton guifg=#282828 guibg=#bdae93 gui=bold cterm=bold
  hi ToolbarLine guifg=NONE guibg=#bdae93 gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#bdae93 gui=NONE cterm=NONE
  hi WildMenu guifg=#076678 guibg=#d5c4a1 gui=bold cterm=bold
  hi Conceal guifg=#076678 guibg=NONE gui=NONE cterm=NONE
  hi Cursor guifg=NONE guibg=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi DiffAdd guifg=#79740e guibg=#f9f5d7 gui=reverse cterm=reverse
  hi DiffChange guifg=#427b58 guibg=#f9f5d7 gui=reverse cterm=reverse
  hi DiffDelete guifg=#9d0006 guibg=#f9f5d7 gui=reverse cterm=reverse
  hi DiffText guifg=#b57614 guibg=#f9f5d7 gui=reverse cterm=reverse
  hi Directory guifg=#79740e guibg=NONE gui=bold cterm=bold
  hi EndOfBuffer guifg=#f9f5d7 guibg=NONE gui=NONE cterm=NONE
  hi IncSearch guifg=#af3a03 guibg=#f9f5d7 gui=reverse cterm=reverse
  hi ModeMsg guifg=#b57614 guibg=NONE gui=bold cterm=bold
  hi MoreMsg guifg=#b57614 guibg=NONE gui=bold cterm=bold
  hi Question guifg=#af3a03 guibg=NONE gui=bold cterm=bold
  hi Search guifg=#b57614 guibg=#f9f5d7 gui=reverse cterm=reverse
  hi SpellBad guifg=#9d0006 guibg=NONE guisp=#9d0006 gui=italic,undercurl cterm=italic,underline
  hi SpellCap guifg=#076678 guibg=NONE guisp=#076678 gui=italic,undercurl cterm=italic,underline
  hi SpellLocal guifg=#427b58 guibg=NONE guisp=#427b58 gui=italic,undercurl cterm=italic,underline
  hi SpellRare guifg=#8f3f71 guibg=NONE guisp=#8f3f71 gui=italic,undercurl cterm=italic,underline
  hi Title guifg=#79740e guibg=NONE gui=bold cterm=bold
  hi WarningMsg guifg=#9d0006 guibg=NONE gui=bold cterm=bold
  hi Boolean guifg=#8f3f71 guibg=NONE gui=NONE cterm=NONE
  hi Character guifg=#8f3f71 guibg=NONE gui=NONE cterm=NONE
  hi Conditional guifg=#9d0006 guibg=NONE gui=NONE cterm=NONE
  hi Constant guifg=#8f3f71 guibg=NONE gui=NONE cterm=NONE
  hi Define guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
  hi Debug guifg=#9d0006 guibg=NONE gui=NONE cterm=NONE
  hi Delimiter guifg=#af3a03 guibg=NONE gui=NONE cterm=NONE
  hi Error guifg=#9d0006 guibg=#f9f5d7 gui=bold,reverse cterm=bold,reverse
  hi Exception guifg=#9d0006 guibg=NONE gui=NONE cterm=NONE
  hi Float guifg=#8f3f71 guibg=NONE gui=NONE cterm=NONE
  hi Function guifg=#79740e guibg=NONE gui=bold cterm=bold
  hi Identifier guifg=#076678 guibg=NONE gui=NONE cterm=NONE
  hi Ignore guifg=fg guibg=NONE gui=NONE cterm=NONE
  hi Include guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
  hi Keyword guifg=#9d0006 guibg=NONE gui=NONE cterm=NONE
  hi Label guifg=#9d0006 guibg=NONE gui=NONE cterm=NONE
  hi Macro guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
  hi Number guifg=#8f3f71 guibg=NONE gui=NONE cterm=NONE
  hi Operator guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
  hi PreCondit guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
  hi Repeat guifg=#9d0006 guibg=NONE gui=NONE cterm=NONE
  hi SpecialChar guifg=#9d0006 guibg=NONE gui=NONE cterm=NONE
  hi SpecialComment guifg=#9d0006 guibg=NONE gui=NONE cterm=NONE
  hi Statement guifg=#9d0006 guibg=NONE gui=NONE cterm=NONE
  hi StorageClass guifg=#af3a03 guibg=NONE gui=NONE cterm=NONE
  hi Special guifg=#af3a03 guibg=NONE gui=italic cterm=italic
  hi String guifg=#79740e guibg=NONE gui=italic cterm=italic
  hi Structure guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
  hi Todo guifg=fg guibg=#f9f5d7 gui=bold,italic cterm=bold,italic
  hi Type guifg=#b57614 guibg=NONE gui=NONE cterm=NONE
  hi Typedef guifg=#b57614 guibg=NONE gui=NONE cterm=NONE
  hi Underlined guifg=#076678 guibg=NONE gui=underline cterm=underline
  hi CursorIM guifg=NONE guibg=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  if !s:italics
    hi Comment gui=NONE cterm=NONE
    hi Folded gui=NONE cterm=NONE
    hi SpellBad gui=undercurl cterm=underline
    hi SpellCap gui=undercurl cterm=underline
    hi SpellLocal gui=undercurl cterm=underline
    hi SpellRare gui=undercurl cterm=underline
    hi Special gui=NONE cterm=NONE
    hi String gui=NONE cterm=NONE
    hi Todo gui=bold cterm=bold
  endif
  if !get(g:, 'gruvbox_italicize_strings', 1)
    hi Special gui=NONE cterm=NONE
    hi String gui=NONE cterm=NONE
  endif
  if !get(g:, 'gruvbox_bold', 1)
    hi Directory gui=NONE cterm=NONE
    hi Error gui=reverse cterm=reverse
    hi ErrorMsg gui=NONE cterm=NONE
    hi Function gui=NONE cterm=NONE
    hi MatchParen gui=underline cterm=underline
    hi ModeMsg gui=NONE cterm=NONE
    hi MoreMsg gui=NONE cterm=NONE
    hi PmenuSel gui=NONE cterm=NONE
    hi Question gui=NONE cterm=NONE
    hi Title gui=NONE cterm=NONE
    hi Todo gui=italic cterm=italic
    hi ToolbarButton gui=NONE cterm=NONE
    hi WarningMsg gui=NONE cterm=NONE
    hi WildMenu gui=NONE cterm=NONE
  endif
  hi NormalMode guifg=#7c6f64 guibg=#f9f5d7 gui=reverse cterm=reverse
  hi InsertMode guifg=#076678 guibg=#f9f5d7 gui=reverse cterm=reverse
  hi ReplaceMode guifg=#427b58 guibg=#f9f5d7 gui=reverse cterm=reverse
  hi VisualMode guifg=#af3a03 guibg=#f9f5d7 gui=reverse cterm=reverse
  hi CommandMode guifg=#8f3f71 guibg=#f9f5d7 gui=reverse cterm=reverse
  hi Warnings guifg=#af3a03 guibg=#f9f5d7 gui=reverse cterm=reverse
  if has('nvim')
    hi! link TermCursor Cursor
    hi TermCursorNC guifg=#ebdbb2 guibg=#3c3836 gui=NONE cterm=NONE
  endif
  if !(get(g:, 'gruvbox_plugin_hi_groups', 0) || get(g:, 'gruvbox_filetype_hi_groups', 0))
    finish
  endif
  if get(g:, "gruvbox_plugin_hi_groups", 0)
    hi CocErrorSign guifg=#9d0006 guibg=#f9f5d7 gui=NONE cterm=NONE
    hi CocWarningSign guifg=#b57614 guibg=#f9f5d7 gui=NONE cterm=NONE
    hi CocInfoSign guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi CocHintSign guifg=#d5c4a1 guibg=NONE gui=NONE cterm=NONE
    hi CocErrorFloat guifg=#9d0006 guibg=NONE gui=NONE cterm=NONE
    hi CocWarningFloat guifg=#b57614 guibg=NONE gui=NONE cterm=NONE
    hi CocInfoFloat guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi CocHintFloat guifg=#8f3f71 guibg=NONE gui=NONE cterm=NONE
    hi CocSelectedText guifg=#ebdbb2 guibg=#f9f5d7 gui=NONE cterm=NONE
    hi CocCodeLens guifg=#d5c4a1 guibg=NONE gui=NONE cterm=NONE
    let g:vimshell_escape_colors = [
          \ '#a89984', '#9d0006', '#79740e', '#b57614',
          \ '#076678', '#8f3f71', '#427b58', '#7c6f64',
          \ '#f9f5d7', '#9d0006', '#79740e', '#af3a03',
          \ '#076678', '#8f3f71', '#427b58', '#282828'
          \ ]
  endif
  if get(g:, "gruvbox_filetype_hi_groups", 0)
    hi diffAdded guifg=#79740e guibg=NONE gui=NONE cterm=NONE
    hi diffRemoved guifg=#9d0006 guibg=NONE gui=NONE cterm=NONE
    hi diffChanged guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi diffFile guifg=#af3a03 guibg=NONE gui=NONE cterm=NONE
    hi diffNewFile guifg=#b57614 guibg=NONE gui=NONE cterm=NONE
    hi diffLine guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi htmlTag guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi htmlEndTag guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi htmlTagName guifg=#427b58 guibg=NONE gui=bold cterm=bold
    hi htmlArg guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi htmlScriptTag guifg=#8f3f71 guibg=NONE gui=NONE cterm=NONE
    hi htmlTagN guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi htmlSpecialTagName guifg=#427b58 guibg=NONE gui=bold cterm=bold
    hi htmlLink guifg=#7c6f64 guibg=NONE gui=underline cterm=underline
    hi htmlSpecialChar guifg=#af3a03 guibg=NONE gui=NONE cterm=NONE
    hi htmlBold guifg=fg guibg=#f9f5d7 gui=bold cterm=bold
    hi htmlBoldUnderline guifg=fg guibg=#f9f5d7 gui=bold,underline cterm=bold,underline
    hi htmlBoldItalic guifg=fg guibg=#f9f5d7 gui=bold,italic cterm=bold,italic
    hi htmlBoldUnderlineItalic guifg=fg guibg=#f9f5d7 gui=bold,italic,underline cterm=bold,italic,underline
    hi htmlUnderline guifg=fg guibg=#f9f5d7 gui=underline cterm=underline
    hi htmlUnderlineItalic guifg=fg guibg=#f9f5d7 gui=italic,underline cterm=italic,underline
    hi htmlItalic guifg=fg guibg=#f9f5d7 gui=italic cterm=italic
    hi xmlTag guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi xmlEndTag guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi xmlTagName guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi xmlEqual guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi docbkKeyword guifg=#427b58 guibg=NONE gui=bold cterm=bold
    hi xmlDocTypeDecl guifg=#928374 guibg=NONE gui=NONE cterm=NONE
    hi xmlDocTypeKeyword guifg=#8f3f71 guibg=NONE gui=NONE cterm=NONE
    hi xmlCdataStart guifg=#928374 guibg=NONE gui=NONE cterm=NONE
    hi xmlCdataCdata guifg=#8f3f71 guibg=NONE gui=NONE cterm=NONE
    hi dtdFunction guifg=#928374 guibg=NONE gui=NONE cterm=NONE
    hi dtdTagName guifg=#8f3f71 guibg=NONE gui=NONE cterm=NONE
    hi xmlAttrib guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi xmlProcessingDelim guifg=#928374 guibg=NONE gui=NONE cterm=NONE
    hi dtdParamEntityPunct guifg=#928374 guibg=NONE gui=NONE cterm=NONE
    hi dtdParamEntityDPunct guifg=#928374 guibg=NONE gui=NONE cterm=NONE
    hi xmlAttribPunct guifg=#928374 guibg=NONE gui=NONE cterm=NONE
    hi xmlEntity guifg=#af3a03 guibg=NONE gui=NONE cterm=NONE
    hi xmlEntityPunct guifg=#af3a03 guibg=NONE gui=NONE cterm=NONE
    hi vimCommentTitle guifg=#7c6f64 guibg=NONE gui=bold cterm=bold
    hi vimNotation guifg=#af3a03 guibg=NONE gui=NONE cterm=NONE
    hi vimBracket guifg=#af3a03 guibg=NONE gui=NONE cterm=NONE
    hi vimMapModKey guifg=#af3a03 guibg=NONE gui=NONE cterm=NONE
    hi vimFuncSID guifg=#665c54 guibg=NONE gui=NONE cterm=NONE
    hi vimSetSep guifg=#665c54 guibg=NONE gui=NONE cterm=NONE
    hi vimSep guifg=#665c54 guibg=NONE gui=NONE cterm=NONE
    hi vimContinue guifg=#665c54 guibg=NONE gui=NONE cterm=NONE
    hi clojureKeyword guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi clojureCond guifg=#af3a03 guibg=NONE gui=NONE cterm=NONE
    hi clojureSpecial guifg=#af3a03 guibg=NONE gui=NONE cterm=NONE
    hi clojureDefine guifg=#af3a03 guibg=NONE gui=NONE cterm=NONE
    hi clojureFunc guifg=#b57614 guibg=NONE gui=NONE cterm=NONE
    hi clojureRepeat guifg=#b57614 guibg=NONE gui=NONE cterm=NONE
    hi clojureCharacter guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi clojureStringEscape guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi clojureException guifg=#9d0006 guibg=NONE gui=NONE cterm=NONE
    hi clojureRegexp guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi clojureRegexpEscape guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi clojureRegexpCharClass guifg=#665c54 guibg=NONE gui=bold cterm=bold
    hi! link clojureRegexpMod clojureRegexpCharClass
    hi! link clojureRegexpQuantifier clojureRegexpCharClass
    hi clojureParen guifg=#665c54 guibg=NONE gui=NONE cterm=NONE
    hi clojureAnonArg guifg=#b57614 guibg=NONE gui=NONE cterm=NONE
    hi clojureVariable guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi clojureMacro guifg=#af3a03 guibg=NONE gui=NONE cterm=NONE
    hi clojureMeta guifg=#b57614 guibg=NONE gui=NONE cterm=NONE
    hi clojureDeref guifg=#b57614 guibg=NONE gui=NONE cterm=NONE
    hi clojureQuote guifg=#b57614 guibg=NONE gui=NONE cterm=NONE
    hi clojureUnquote guifg=#b57614 guibg=NONE gui=NONE cterm=NONE
    hi cOperator guifg=#8f3f71 guibg=NONE gui=NONE cterm=NONE
    hi cStructure guifg=#af3a03 guibg=NONE gui=NONE cterm=NONE
    hi pythonBuiltin guifg=#af3a03 guibg=NONE gui=NONE cterm=NONE
    hi pythonBuiltinObj guifg=#af3a03 guibg=NONE gui=NONE cterm=NONE
    hi pythonBuiltinFunc guifg=#af3a03 guibg=NONE gui=NONE cterm=NONE
    hi pythonFunction guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi pythonDecorator guifg=#9d0006 guibg=NONE gui=NONE cterm=NONE
    hi pythonInclude guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi pythonImport guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi pythonRun guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi pythonCoding guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi pythonOperator guifg=#9d0006 guibg=NONE gui=NONE cterm=NONE
    hi pythonException guifg=#9d0006 guibg=NONE gui=NONE cterm=NONE
    hi pythonExceptions guifg=#8f3f71 guibg=NONE gui=NONE cterm=NONE
    hi pythonBoolean guifg=#8f3f71 guibg=NONE gui=NONE cterm=NONE
    hi pythonDot guifg=#665c54 guibg=NONE gui=NONE cterm=NONE
    hi pythonConditional guifg=#9d0006 guibg=NONE gui=NONE cterm=NONE
    hi pythonRepeat guifg=#9d0006 guibg=NONE gui=NONE cterm=NONE
    hi pythonDottedName guifg=#79740e guibg=NONE gui=bold cterm=bold
    hi cssBraces guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi cssFunctionName guifg=#b57614 guibg=NONE gui=NONE cterm=NONE
    hi cssIdentifier guifg=#af3a03 guibg=NONE gui=NONE cterm=NONE
    hi cssClassName guifg=#79740e guibg=NONE gui=NONE cterm=NONE
    hi cssColor guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi cssSelectorOp guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi cssSelectorOp2 guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi cssImportant guifg=#79740e guibg=NONE gui=NONE cterm=NONE
    hi cssVendor guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi cssTextProp guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi cssAnimationProp guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi cssUIProp guifg=#b57614 guibg=NONE gui=NONE cterm=NONE
    hi cssTransformProp guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi cssTransitionProp guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi cssPrintProp guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi cssPositioningProp guifg=#b57614 guibg=NONE gui=NONE cterm=NONE
    hi cssBoxProp guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi cssFontDescriptorProp guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi cssFlexibleBoxProp guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi cssBorderOutlineProp guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi cssBackgroundProp guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi cssMarginProp guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi cssListProp guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi cssTableProp guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi cssFontProp guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi cssPaddingProp guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi cssDimensionProp guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi cssRenderProp guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi cssColorProp guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi cssGeneratedContentProp guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi javaScriptBraces guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi javaScriptFunction guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi javaScriptIdentifier guifg=#9d0006 guibg=NONE gui=NONE cterm=NONE
    hi javaScriptMember guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi javaScriptNumber guifg=#8f3f71 guibg=NONE gui=NONE cterm=NONE
    hi javaScriptNull guifg=#8f3f71 guibg=NONE gui=NONE cterm=NONE
    hi javaScriptParens guifg=#665c54 guibg=NONE gui=NONE cterm=NONE
    hi javascriptImport guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi javascriptExport guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi javascriptClassKeyword guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi javascriptClassExtends guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi javascriptDefault guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi javascriptClassName guifg=#b57614 guibg=NONE gui=NONE cterm=NONE
    hi javascriptClassSuperName guifg=#b57614 guibg=NONE gui=NONE cterm=NONE
    hi javascriptGlobal guifg=#b57614 guibg=NONE gui=NONE cterm=NONE
    hi javascriptEndColons guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi javascriptFuncArg guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi javascriptGlobalMethod guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi javascriptNodeGlobal guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi javascriptBOMWindowProp guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi javascriptArrayMethod guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi javascriptArrayStaticMethod guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi javascriptCacheMethod guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi javascriptDateMethod guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi javascriptMathStaticMethod guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi javascriptURLUtilsProp guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi javascriptBOMNavigatorProp guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi javascriptDOMDocMethod guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi javascriptDOMDocProp guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi javascriptBOMLocationMethod guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi javascriptBOMWindowMethod guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi javascriptStringMethod guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi javascriptVariable guifg=#af3a03 guibg=NONE gui=NONE cterm=NONE
    hi javascriptIdentifier guifg=#af3a03 guibg=NONE gui=NONE cterm=NONE
    hi javascriptClassSuper guifg=#af3a03 guibg=NONE gui=NONE cterm=NONE
    hi javascriptFuncKeyword guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi javascriptAsyncFunc guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi javascriptClassStatic guifg=#af3a03 guibg=NONE gui=NONE cterm=NONE
    hi javascriptOperator guifg=#9d0006 guibg=NONE gui=NONE cterm=NONE
    hi javascriptForOperator guifg=#9d0006 guibg=NONE gui=NONE cterm=NONE
    hi javascriptYield guifg=#9d0006 guibg=NONE gui=NONE cterm=NONE
    hi javascriptExceptions guifg=#9d0006 guibg=NONE gui=NONE cterm=NONE
    hi javascriptMessage guifg=#9d0006 guibg=NONE gui=NONE cterm=NONE
    hi javascriptTemplateSB guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi javascriptTemplateSubstitution guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi javascriptLabel guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi javascriptObjectLabel guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi javascriptPropertyName guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi javascriptLogicSymbols guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi javascriptArrowFunc guifg=#b57614 guibg=NONE gui=NONE cterm=NONE
    hi javascriptDocParamName guifg=#7c6f64 guibg=NONE gui=NONE cterm=NONE
    hi javascriptDocTags guifg=#7c6f64 guibg=NONE gui=NONE cterm=NONE
    hi javascriptDocNotation guifg=#7c6f64 guibg=NONE gui=NONE cterm=NONE
    hi javascriptDocParamType guifg=#7c6f64 guibg=NONE gui=NONE cterm=NONE
    hi javascriptDocNamedParamType guifg=#7c6f64 guibg=NONE gui=NONE cterm=NONE
    hi javascriptBrackets guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi javascriptDOMElemAttrs guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi javascriptDOMEventMethod guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi javascriptDOMNodeMethod guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi javascriptDOMStorageMethod guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi javascriptHeadersMethod guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi javascriptAsyncFuncKeyword guifg=#9d0006 guibg=NONE gui=NONE cterm=NONE
    hi javascriptAwaitFuncKeyword guifg=#9d0006 guibg=NONE gui=NONE cterm=NONE
    hi jsImport guifg=#9d0006 guibg=NONE gui=NONE cterm=NONE
    hi jsExport guifg=#9d0006 guibg=NONE gui=NONE cterm=NONE
    hi jsFrom guifg=#9d0006 guibg=NONE gui=NONE cterm=NONE
    hi jsThis guifg=#8f3f71 guibg=NONE gui=NONE cterm=NONE
    hi jsParen guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi jsOperator guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi jsSpreadOperator guifg=#79740e guibg=NONE gui=NONE cterm=NONE
    hi jsSpreadExpression guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi jsClassKeyword guifg=#9d0006 guibg=NONE gui=NONE cterm=NONE
    hi jsClassProperty guifg=#79740e guibg=NONE gui=NONE cterm=NONE
    hi jsExtendsKeyword guifg=#9d0006 guibg=NONE gui=NONE cterm=NONE
    hi jsExportDefault guifg=#af3a03 guibg=NONE gui=bold cterm=bold
    hi jsTemplateBraces guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi jsGlobalNodeObjects guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi jsGlobalObjects guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi jsFunction guifg=#79740e guibg=NONE gui=NONE cterm=NONE
    hi jsFuncParens guifg=#8f3f71 guibg=NONE gui=NONE cterm=NONE
    hi jsFuncBlock guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi jsParens guifg=#665c54 guibg=NONE gui=NONE cterm=NONE
    hi jsNull guifg=#8f3f71 guibg=NONE gui=NONE cterm=NONE
    hi jsUndefined guifg=#8f3f71 guibg=NONE gui=NONE cterm=NONE
    hi jsClassDefinition guifg=#b57614 guibg=NONE gui=NONE cterm=NONE
    hi jsFunctionKey guifg=#79740e guibg=NONE gui=NONE cterm=NONE
    hi jsBracket guifg=#9d0006 guibg=NONE gui=NONE cterm=NONE
    hi jsObjectColon guifg=#9d0006 guibg=NONE gui=NONE cterm=NONE
    hi jsObjectProp guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi jsFuncBraces guifg=#79740e guibg=NONE gui=NONE cterm=NONE
    hi jsVariableDef guifg=#b57614 guibg=NONE gui=NONE cterm=NONE
    hi jsObjectValue guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi jsDestructuringBlock guifg=#b57614 guibg=NONE gui=NONE cterm=NONE
    hi jsParenIfElse guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi jsClassBlock guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi jsFutureKeys guifg=#af3a03 guibg=NONE gui=bold cterm=bold
    hi jsStorageClass guifg=#af3a03 guibg=NONE gui=NONE cterm=NONE
    hi jsModuleKeyword guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi jsObjectShorthandProp guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi jsxRegion guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi jsxTagName guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi jsxComponentName guifg=#b57614 guibg=NONE gui=NONE cterm=NONE
    hi jsxEscapeJsAttributes guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi jsxEscapeJsContent guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi jsxAttrib guifg=#b57614 guibg=NONE gui=NONE cterm=NONE
    hi jsxAttributeBraces guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi jsxEqual guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi jsxString guifg=#79740e guibg=NONE gui=NONE cterm=NONE
    hi jsxCloseTag guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi jsxEndTag guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi jsxEndString guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi jsxCloseString guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi jsxIfOperator guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi jsxElseOperator guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi jsxDot guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi jsxNamespace guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi jsxPunct guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi typeScriptReserved guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi typeScriptLabel guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi typeScriptFuncKeyword guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi typeScriptIdentifier guifg=#af3a03 guibg=NONE gui=NONE cterm=NONE
    hi typeScriptBraces guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi typeScriptEndColons guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi typeScriptDOMObjects guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi typeScriptAjaxMethods guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi typeScriptLogicSymbols guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi! link typeScriptDocSeeTag Comment
    hi! link typeScriptDocParam Comment
    hi! link typeScriptDocTags vimCommentTitle
    hi typeScriptGlobalObjects guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi typeScriptParens guifg=#665c54 guibg=NONE gui=NONE cterm=NONE
    hi typeScriptOpSymbols guifg=#665c54 guibg=NONE gui=NONE cterm=NONE
    hi typeScriptHtmlElemProperties guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi typeScriptNull guifg=#8f3f71 guibg=NONE gui=NONE cterm=NONE
    hi typeScriptInterpolationDelimiter guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi purescriptModuleKeyword guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi purescriptModuleName guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi purescriptWhere guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi purescriptDelimiter guifg=#7c6f64 guibg=NONE gui=NONE cterm=NONE
    hi purescriptType guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi purescriptImportKeyword guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi purescriptHidingKeyword guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi purescriptAsKeyword guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi purescriptStructure guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi purescriptOperator guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi purescriptTypeVar guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi purescriptConstructor guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi purescriptFunction guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi purescriptConditional guifg=#af3a03 guibg=NONE gui=NONE cterm=NONE
    hi purescriptBacktick guifg=#af3a03 guibg=NONE gui=NONE cterm=NONE
    hi coffeeExtendedOp guifg=#665c54 guibg=NONE gui=NONE cterm=NONE
    hi coffeeSpecialOp guifg=#665c54 guibg=NONE gui=NONE cterm=NONE
    hi coffeeCurly guifg=#af3a03 guibg=NONE gui=NONE cterm=NONE
    hi coffeeParen guifg=#665c54 guibg=NONE gui=NONE cterm=NONE
    hi coffeeBracket guifg=#af3a03 guibg=NONE gui=NONE cterm=NONE
    hi rubyStringDelimiter guifg=#79740e guibg=NONE gui=NONE cterm=NONE
    hi rubyInterpolationDelimiter guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi objcTypeModifier guifg=#9d0006 guibg=NONE gui=NONE cterm=NONE
    hi objcDirective guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi goDirective guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi goConstants guifg=#8f3f71 guibg=NONE gui=NONE cterm=NONE
    hi goDeclaration guifg=#9d0006 guibg=NONE gui=NONE cterm=NONE
    hi goDeclType guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi goBuiltins guifg=#af3a03 guibg=NONE gui=NONE cterm=NONE
    hi luaIn guifg=#9d0006 guibg=NONE gui=NONE cterm=NONE
    hi luaFunction guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi luaTable guifg=#af3a03 guibg=NONE gui=NONE cterm=NONE
    hi moonSpecialOp guifg=#665c54 guibg=NONE gui=NONE cterm=NONE
    hi moonExtendedOp guifg=#665c54 guibg=NONE gui=NONE cterm=NONE
    hi moonFunction guifg=#665c54 guibg=NONE gui=NONE cterm=NONE
    hi moonObject guifg=#b57614 guibg=NONE gui=NONE cterm=NONE
    hi javaAnnotation guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi javaDocTags guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi! link javaCommentTitle vimCommentTitle
    hi javaParen guifg=#665c54 guibg=NONE gui=NONE cterm=NONE
    hi javaParen1 guifg=#665c54 guibg=NONE gui=NONE cterm=NONE
    hi javaParen2 guifg=#665c54 guibg=NONE gui=NONE cterm=NONE
    hi javaParen3 guifg=#665c54 guibg=NONE gui=NONE cterm=NONE
    hi javaParen4 guifg=#665c54 guibg=NONE gui=NONE cterm=NONE
    hi javaParen5 guifg=#665c54 guibg=NONE gui=NONE cterm=NONE
    hi javaOperator guifg=#af3a03 guibg=NONE gui=NONE cterm=NONE
    hi javaVarArg guifg=#79740e guibg=NONE gui=NONE cterm=NONE
    hi! link elixirDocString Comment
    hi elixirStringDelimiter guifg=#79740e guibg=NONE gui=NONE cterm=NONE
    hi elixirInterpolationDelimiter guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi elixirModuleDeclaration guifg=#b57614 guibg=NONE gui=NONE cterm=NONE
    hi scalaNameDefinition guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi scalaCaseFollowing guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi scalaCapitalWord guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi scalaTypeExtension guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi scalaKeyword guifg=#9d0006 guibg=NONE gui=NONE cterm=NONE
    hi scalaKeywordModifier guifg=#9d0006 guibg=NONE gui=NONE cterm=NONE
    hi scalaSpecial guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi scalaOperator guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi scalaTypeDeclaration guifg=#b57614 guibg=NONE gui=NONE cterm=NONE
    hi scalaTypeTypePostDeclaration guifg=#b57614 guibg=NONE gui=NONE cterm=NONE
    hi scalaInstanceDeclaration guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi scalaInterpolation guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi markdownItalic guifg=#665c54 guibg=NONE gui=italic cterm=italic
    hi markdownH1 guifg=#79740e guibg=NONE gui=bold cterm=bold
    hi markdownH2 guifg=#79740e guibg=NONE gui=bold cterm=bold
    hi markdownH3 guifg=#b57614 guibg=NONE gui=bold cterm=bold
    hi markdownH4 guifg=#b57614 guibg=NONE gui=bold cterm=bold
    hi markdownH5 guifg=#b57614 guibg=NONE gui=NONE cterm=NONE
    hi markdownH6 guifg=#b57614 guibg=NONE gui=NONE cterm=NONE
    hi markdownCode guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi markdownCodeBlock guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi markdownCodeDelimiter guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi markdownBlockquote guifg=#928374 guibg=NONE gui=NONE cterm=NONE
    hi markdownListMarker guifg=#928374 guibg=NONE gui=NONE cterm=NONE
    hi markdownOrderedListMarker guifg=#928374 guibg=NONE gui=NONE cterm=NONE
    hi markdownRule guifg=#928374 guibg=NONE gui=NONE cterm=NONE
    hi markdownHeadingRule guifg=#928374 guibg=NONE gui=NONE cterm=NONE
    hi markdownUrlDelimiter guifg=#665c54 guibg=NONE gui=NONE cterm=NONE
    hi markdownLinkDelimiter guifg=#665c54 guibg=NONE gui=NONE cterm=NONE
    hi markdownLinkTextDelimiter guifg=#665c54 guibg=NONE gui=NONE cterm=NONE
    hi markdownHeadingDelimiter guifg=#af3a03 guibg=NONE gui=NONE cterm=NONE
    hi markdownUrl guifg=#8f3f71 guibg=NONE gui=NONE cterm=NONE
    hi markdownUrlTitleDelimiter guifg=#79740e guibg=NONE gui=NONE cterm=NONE
    hi markdownLinkText guifg=#928374 guibg=NONE gui=underline cterm=underline
    hi! link markdownIdDeclaration markdownLinkText
    hi haskellType guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi haskellIdentifier guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi haskellSeparator guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi haskellDelimiter guifg=#7c6f64 guibg=NONE gui=NONE cterm=NONE
    hi haskellOperators guifg=#076678 guibg=NONE gui=NONE cterm=NONE
    hi haskellBacktick guifg=#af3a03 guibg=NONE gui=NONE cterm=NONE
    hi haskellStatement guifg=#af3a03 guibg=NONE gui=NONE cterm=NONE
    hi haskellConditional guifg=#af3a03 guibg=NONE gui=NONE cterm=NONE
    hi haskellLet guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi haskellDefault guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi haskellWhere guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi haskellBottom guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi haskellBlockKeywords guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi haskellImportKeywords guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi haskellDeclKeyword guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi haskellDeriving guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi haskellAssocType guifg=#427b58 guibg=NONE gui=NONE cterm=NONE
    hi haskellNumber guifg=#8f3f71 guibg=NONE gui=NONE cterm=NONE
    hi haskellPragma guifg=#8f3f71 guibg=NONE gui=NONE cterm=NONE
    hi haskellString guifg=#79740e guibg=NONE gui=NONE cterm=NONE
    hi haskellChar guifg=#79740e guibg=NONE gui=NONE cterm=NONE
    hi jsonKeyword guifg=#79740e guibg=NONE gui=NONE cterm=NONE
    hi jsonQuote guifg=#79740e guibg=NONE gui=NONE cterm=NONE
    hi jsonBraces guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    hi jsonString guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
    if !s:italics
      hi htmlBoldItalic gui=bold cterm=bold
      hi htmlBoldUnderlineItalic gui=bold,underline cterm=bold,underline
      hi htmlUnderlineItalic gui=underline cterm=underline
      hi htmlItalic gui=NONE cterm=NONE
      hi markdownItalic gui=NONE cterm=NONE
    endif
    if !get(g:, 'gruvbox_bold', 1)
      hi htmlTagName gui=NONE cterm=NONE
      hi htmlSpecialTagName gui=NONE cterm=NONE
      hi htmlBold gui=NONE cterm=NONE
      hi htmlBoldUnderline gui=underline cterm=underline
      hi htmlBoldItalic gui=italic cterm=italic
      hi htmlBoldUnderlineItalic gui=underline,italic cterm=underline,italic
      hi docbkKeyword gui=NONE cterm=NONE
      hi vimCommentTitle gui=NONE cterm=NONE
      hi clojureRegexpCharClass gui=NONE cterm=NONE
      hi pythonDottedName gui=NONE cterm=NONE
      hi jsExportDefault gui=NONE cterm=NONE
      hi jsFutureKeys gui=NONE cterm=NONE
      hi markdownH1 gui=NONE cterm=NONE
      hi markdownH2 gui=NONE cterm=NONE
      hi markdownH3 gui=NONE cterm=NONE
      hi markdownH4 gui=NONE cterm=NONE
    endif
  endif
  unlet s:t_Co s:italics
  finish
endif

" Color: neutralred        rgb(204,  36,  29)    160 DarkRed
" Color: neutralgreen      rgb(152, 151,  26)    100 DarkGreen
" Color: neutralyellow     rgb(215, 153,  33)    172 DarkYellow
" Color: neutralblue       rgb( 69, 133, 136)    66  DarkBlue
" Color: neutralpurple     rgb(177,  98, 134)    132 DarkMagenta
" Color: neutralaqua       rgb(104, 157, 106)    71  DarkCyan
" Color: neutralorange     rgb(214,  93,  14)    166
" Background: dark
" Color: bg0 rgb(29,32,33) 234 Black
" Color: bg1             rgb(60,  56,  54)     237 DarkGray
" Color: bg2             rgb(80,  73,  69)     239
" Color: bg3             rgb(102, 92,  84)      59
" Color: bg4             rgb(124, 111, 100)    243
" Color: fg0             rgb(251, 241, 199)    230
" Color: fg1             rgb(235, 219, 178)    187 White
" Color: fg2             rgb(213, 196, 161)    187
" Color: fg3             rgb(189, 174, 147)    144
" Color: fg4             rgb(168, 153, 132)    137 Gray
" Color: grey            rgb(146, 131, 116)    102 DarkGray
" Color: red             rgb(251, 73,  52)     203 Red
" Color: green           rgb(184, 187, 38)     142 Green
" Color: yellow          rgb(250, 189, 47)     214 Yellow
" Color: blue            rgb(131, 165, 152)    109 Blue
" Color: purple          rgb(211, 134, 155)    175 Magenta
" Color: aqua            rgb(142, 192, 124)    107 Cyan
" Color: orange          rgb(254, 128, 25)     208 Magenta
" Term colors: bg0 neutralred neutralgreen neutralyellow
" Term colors: neutralblue neutralpurple neutralaqua fg4
" Term colors: grey red green yellow blue purple aqua fg1
" Background: light
" Color: bg0 rgb(249,245,215)   229 White
" Color: bg1 rgb(235, 219, 178) 187 Grey
" Color: bg2 rgb(213, 196, 161) 187
" Color: bg3               rgb(189, 174, 147)    144
" Color: bg4               rgb(168, 153, 132)    137
" Color: fg0               rgb( 40,  40,  40)    235 DarkGray
" Color: fg1               rgb( 60,  56,  54)    237 Black
" Color: fg2               rgb( 80,  56,  54)    237
" Color: fg3               rgb(102,  92,  84)     59
" Color: fg4               rgb(124, 111, 100)    243 Black
" Color: grey              rgb(146, 131, 116)    102 DarkGray
" Color: red               rgb(157,   0,   6)    124 Red
" Color: green             rgb(121, 116,  14)    100 Green
" Color: yellow            rgb(181, 118,  20)    172 Yellow
" Color: blue              rgb(  7, 102, 120)    23  Blue
" Color: purple            rgb(143,  63, 113)    126 Magenta
" Color: aqua              rgb( 66, 123,  88)    29  Cyan
" Color: orange            rgb(175,  58,   3)    124 Magenta
" Term colors: bg0 neutralred neutralgreen neutralyellow
" Term colors: neutralblue neutralpurple neutralaqua fg4
" Term colors: grey red green yellow blue purple aqua fg1
" Background: any
" vim: et ts=2 sw=2
